name: BARTApp
options:
  bundleIdPrefix: com.openclaw
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "16.3"

settings:
  base:
    SWIFT_VERSION: "5.0"
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

targets:
  BARTApp:
    type: application
    platform: iOS
    sources:
      - BARTApp
    settings:
      base:
        INFOPLIST_FILE: BARTApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.openclaw.bartapp
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
