import Foundation

/// Payload encoded in QR codes generated by `openclaw devices pair --qr`
struct QRPairingPayload: Codable {
    let gatewayUrl: String
    let token: String?             // Gateway token for authentication
    let role: String
    let verificationCode: String?  // Optional one-time verification code
    let expiresAt: Int             // Unix timestamp in milliseconds

    var isExpired: Bool {
        let expirationDate = Date(timeIntervalSince1970: Double(expiresAt) / 1000)
        return Date() > expirationDate
    }

    var hostAndPort: (host: String, port: Int, useSSL: Bool)? {
        // Parse ws://100.71.145.100:18789 or wss://...
        guard let url = URL(string: gatewayUrl) else { return nil }
        let useSSL = url.scheme == "wss"
        let host = url.host ?? ""
        let port = url.port ?? (useSSL ? 443 : 80)
        return (host, port, useSSL)
    }

    /// Decode from base64-encoded JSON string (QR code content)
    static func decode(from qrContent: String) throws -> QRPairingPayload {
        // First try: content might be raw JSON
        if qrContent.hasPrefix("{") {
            guard let data = qrContent.data(using: .utf8) else {
                throw QRPairingError.invalidBase64
            }
            return try JSONDecoder().decode(QRPairingPayload.self, from: data)
        }

        // Second try: base64 encoded JSON
        guard let data = Data(base64Encoded: qrContent) else {
            // Try URL-safe base64
            let urlSafe = qrContent
                .replacingOccurrences(of: "-", with: "+")
                .replacingOccurrences(of: "_", with: "/")

            // Add padding if needed
            let padded = urlSafe.padding(toLength: ((urlSafe.count + 3) / 4) * 4,
                                          withPad: "=",
                                          startingAt: 0)

            guard let paddedData = Data(base64Encoded: padded) else {
                throw QRPairingError.invalidBase64
            }
            return try JSONDecoder().decode(QRPairingPayload.self, from: paddedData)
        }

        return try JSONDecoder().decode(QRPairingPayload.self, from: data)
    }
}

enum QRPairingError: LocalizedError {
    case invalidBase64
    case invalidJSON
    case expired
    case cameraNotAvailable
    case permissionDenied

    var errorDescription: String? {
        switch self {
        case .invalidBase64:
            return "Invalid QR code format"
        case .invalidJSON:
            return "QR code doesn't contain valid pairing data"
        case .expired:
            return "This pairing code has expired. Generate a new one."
        case .cameraNotAvailable:
            return "Camera is not available on this device"
        case .permissionDenied:
            return "Camera permission is required to scan QR codes"
        }
    }
}
